### ISSUE TITLE
There might be an issue with version of requests specific in setup.py

### ISSUE THREAD

**Issue by chaoranxie** [akamai-open/AkamaiOPEN-edgegrid-python#16]
it looks like edgegrid depends on requests https://github.com/akamai-open/AkamaiOPEN-edgegrid-python/blob/master/setup.py#L12 but it looks like you might have to bump the version number to at least 2.3 https://github.com/kennethreitz/requests/commit/0caa2432123bab2d991e635ce558226d019d7bc7 because the method is_redirect used here https://github.com/akamai-open/AkamaiOPEN-edgegrid-python/blob/master/akamai/edgegrid/edgegrid.py#L205 is not in version 1.2.2

**Comment by jjjhhhlll** [comment]
Thanks for reporting this issue.  I'm taking a look at your change.

**Comment by jjjhhhlll** [comment]
I've updated the package on pypi with this change.
